"""Render a :class:`~app.services.reporting.engine.RunResult` to a file.

Reuses the app's export stack: ``openpyxl`` (as the per-project XLSX tracker does)
and WeasyPrint via :func:`app.services.report_pdf.library_pdf`. Both the tabular
and summary result shapes are supported. These are pure byte producers — the
route wraps the heavy ones (XLSX/PDF) in ``asyncio.to_thread`` behind
:data:`engine.RENDER_SEMAPHORE` so a big render never blocks the event loop.
"""

from __future__ import annotations

import csv
import html
import io
from datetime import date

from openpyxl import Workbook
from openpyxl.styles import Font, PatternFill

from app.services import report_pdf
from app.services.reporting.engine import RunResult


def _table(result: RunResult) -> tuple[list[str], list[list[str]]]:
    """Flatten a RunResult into a (header, rows) pair of display strings."""
    if result.is_summary:
        group_label = result.group_field.label if result.group_field else "All"
        header = [group_label, *result.measure_headers]
        rows = [[g.label, str(g.count), *g.measures] for g in result.group_rows]
        return header, rows
    header = [c.label for c in result.columns]
    rows = [list(r.cells) for r in result.rows]
    return header, rows


def to_csv(result: RunResult) -> bytes:
    header, rows = _table(result)
    buf = io.StringIO()
    writer = csv.writer(buf)
    writer.writerow(header)
    writer.writerows(rows)
    return buf.getvalue().encode("utf-8-sig")  # BOM so Excel opens UTF-8 cleanly


def to_xlsx(result: RunResult, *, title: str) -> bytes:
    header, rows = _table(result)
    wb = Workbook()
    ws = wb.active
    ws.title = "Report"[:31]

    head_font = Font(bold=True, color="FFFFFF")
    head_fill = PatternFill("solid", fgColor="1C1917")
    for col, name in enumerate(header, start=1):
        cell = ws.cell(row=1, column=col, value=name)
        cell.font = head_font
        cell.fill = head_fill
    for r, row in enumerate(rows, start=2):
        for c, value in enumerate(row, start=1):
            ws.cell(row=r, column=c, value=value)

    # Reasonable column widths from the header + a sample of rows.
    for col in range(1, len(header) + 1):
        sample = [header[col - 1]] + [row[col - 1] for row in rows[:50] if col - 1 < len(row)]
        width = min(48, max(12, max((len(str(s)) for s in sample), default=12) + 2))
        ws.column_dimensions[ws.cell(row=1, column=col).column_letter].width = width
    ws.freeze_panes = "A2"

    buf = io.BytesIO()
    wb.save(buf)
    return buf.getvalue()


def result_to_html(result: RunResult, *, title: str, subtitle: str = "") -> str:
    """A self-contained HTML document for the PDF renderer / scheduled email."""
    header, rows = _table(result)
    ths = "".join(f"<th>{html.escape(h)}</th>" for h in header)
    trs = "".join(
        "<tr>" + "".join(f"<td>{html.escape(str(c))}</td>" for c in row) + "</tr>"
        for row in rows
    )
    sub = f"<p class='sub'>{html.escape(subtitle)}</p>" if subtitle else ""
    return f"""<!doctype html><html><head><meta charset="utf-8">
<style>
  body {{ font-family: -apple-system, Segoe UI, sans-serif; color:#1c1917; margin:28px; }}
  h1 {{ font-size:20px; margin:0 0 2px; }}
  .sub {{ color:#78716c; font-size:12px; margin:0 0 16px; }}
  table {{ width:100%; border-collapse:collapse; font-size:11px; }}
  th {{ text-align:left; background:#1c1917; color:#fff; padding:6px 8px; }}
  td {{ padding:5px 8px; border-bottom:1px solid #e7e5e4; }}
  tr:nth-child(even) td {{ background:#fafaf9; }}
  .foot {{ margin-top:16px; color:#a8a29e; font-size:10px; }}
</style></head><body>
  <h1>{html.escape(title)}</h1>{sub}
  <table><thead><tr>{ths}</tr></thead><tbody>{trs}</tbody></table>
  <p class="foot">Generated by Questlog on {date.today().isoformat()} · region-scoped to the recipient.</p>
</body></html>"""


def to_pdf(result: RunResult, *, title: str, subtitle: str = "") -> bytes:
    html_doc = result_to_html(result, title=title, subtitle=subtitle)
    return report_pdf.library_pdf(html_doc)
